---
- name: Metricbeat installation
  hosts: webservers
  become: true
  tasks:

    - name: Download the Metricbeat .deb file.
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Use dpkg to install the .deb file.
      command: dpkg -i metricbeat-7.6.1-amd64.deb

    - name: Update and copy the provided Metricbeat config file.
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable Metricbeat docker
      command: metricbeat modules enable docker

    - name: Setup
      command: metricbeat setup

    - name: Service start
      command: service metricbeat start

    - name: enable service metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes

